name: Release
on: 
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Please specify the release version. i.e. v1.0.0 (must start with "v")'
        required: true
        type: string

permissions:
  contents: read

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check release tag format
        run: |
          if [[ ! "${{ inputs.release_tag }}" =~ ^v[0-9]+(\.[0-9]+)*(-[A-Za-z0-9]+)?$ ]]; then
            echo "Error: release_tag must start with 'v' followed by a version number, optionally with a suffix like -RC1."
            exit 1
          fi

      - name: Create release tag and push (triggers the CI run)
        run: |-
          git tag -a ${{ inputs.release_tag }} -m "${{ inputs.release_tag }}"
          git push origin ${{ inputs.release_tag }}
